/*
 * JS for activityDetail generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return 'abfa3b56-b56f-4a15-ac55-911de764ccdf';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "mapPage",
    "location": "mapPage.html"
}, {
    "name": "activityDetail",
    "location": "activityDetail.html"
}, {
    "name": "profile",
    "location": "profile.html"
}];

activityDetail_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_28': 'activityDetail_mobilegrid_28',
        'mobilegridcell_29': 'activityDetail_mobilegridcell_29',
        'mobilegrid_38': 'activityDetail_mobilegrid_38',
        'mobilegridcell_39': 'activityDetail_mobilegridcell_39',
        'lblActivityLongName': 'activityDetail_lblActivityLongName',
        'mobilegridcell_41': 'activityDetail_mobilegridcell_41',
        'mobilelabel_44': 'activityDetail_mobilelabel_44',
        'mobilegridcell_33': 'activityDetail_mobilegridcell_33',
        'mobilegrid_45': 'activityDetail_mobilegrid_45',
        'mobilegridcell_46': 'activityDetail_mobilegridcell_46',
        'mobilegrid_50': 'activityDetail_mobilegrid_50',
        'mobilegridcell_51': 'activityDetail_mobilegridcell_51',
        'lblAgeLabel': 'activityDetail_lblAgeLabel',
        'mobilegridcell_52': 'activityDetail_mobilegridcell_52',
        'lblDisplayAgeRange': 'activityDetail_lblDisplayAgeRange',
        'mobilegridcell_47': 'activityDetail_mobilegridcell_47',
        'mobilegrid_57': 'activityDetail_mobilegrid_57',
        'mobilegridcell_58': 'activityDetail_mobilegridcell_58',
        'lblTypeLabel': 'activityDetail_lblTypeLabel',
        'mobilegridcell_59': 'activityDetail_mobilegridcell_59',
        'lblDisplayType': 'activityDetail_lblDisplayType',
        'mobilegridcell_48': 'activityDetail_mobilegridcell_48',
        'mobilegrid_70': 'activityDetail_mobilegrid_70',
        'mobilegridcell_71': 'activityDetail_mobilegridcell_71',
        'ldblDayLabel': 'activityDetail_ldblDayLabel',
        'mobilegridcell_72': 'activityDetail_mobilegridcell_72',
        'lblDisplayDay': 'activityDetail_lblDisplayDay',
        'mobilegridcell_49': 'activityDetail_mobilegridcell_49',
        'mobilegrid_77': 'activityDetail_mobilegrid_77',
        'mobilegridcell_78': 'activityDetail_mobilegridcell_78',
        'lblTimeLabel': 'activityDetail_lblTimeLabel',
        'mobilegridcell_79': 'activityDetail_mobilegridcell_79',
        'lblDisplayTime': 'activityDetail_lblDisplayTime',
        'mobilegridcell_35': 'activityDetail_mobilegridcell_35',
        'mobilegrid_64': 'activityDetail_mobilegrid_64',
        'mobilegridcell_65': 'activityDetail_mobilegridcell_65',
        'lblDisplayNarrative': 'activityDetail_lblDisplayNarrative',
        'mobilegridcell_37': 'activityDetail_mobilegridcell_37',
        'lblId': 'activityDetail_lblId'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'activityDetail';

    /*
     * Nonvisual components
     */
    var datasources = [];

    KCActivityDetail = new Appery.DataSource(KCActivityDetailService, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("activityDetail");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['activity', 'name'],
            'ID': 'lblActivityLongName',
            'ATTR': '@'
        }],
        'requestMapping': [{
            'PATH': ['activity-id'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'activityIdentifier'
        }]
    });

    datasources.push(KCActivityDetail);

    /*
     * Events and handlers
     */

    // Before Show
    activityDetail_beforeshow = function() {
        Appery.CurrentScreen = "activityDetail";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_3671_onLoad = activityDetail_onLoad = function() {
        screen_3671_elementsExtraJS();
        setText('activityDetail_lblId', localStorage.getItem('activityIdentifier'));

        // TODO fire device events only if necessary (with JS logic)
        activityDetail_deviceEvents();
        activityDetail_windowEvents();
        screen_3671_elementsEvents();
    }

    // screen window events
    screen_3671_windowEvents = activityDetail_windowEvents = function() {

        $('#activityDetail').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    activityDetail_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_3671_elementsExtraJS = activityDetail_elementsExtraJS = function() {
        // screen (activityDetail) extra code

    }

    // screen elements handler
    screen_3671_elementsEvents = activityDetail_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

    }

    $("#activityDetail").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        activityDetail_beforeshow();
    });

    if (runBeforeShow) {
        activityDetail_beforeshow();
    } else {
        activityDetail_onLoad();
    }

}

$("#activityDetail").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    activityDetail_js();
});