/*
 * JS for startScreen generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return 'abfa3b56-b56f-4a15-ac55-911de764ccdf';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "mapPage",
    "location": "mapPage.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "profile",
    "location": "profile.html"
}];

startScreen_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'searchInput': 'startScreen_searchInput',
        'searchButton': 'startScreen_searchButton',
        'outputGrid': 'startScreen_outputGrid',
        'upperCell': 'startScreen_upperCell',
        'innerGrid': 'startScreen_innerGrid',
        'mobilegridcell_23': 'startScreen_mobilegridcell_23',
        'tweetPicture': 'startScreen_tweetPicture',
        'mobilegridcell_27': 'startScreen_mobilegridcell_27',
        'tweetFrom': 'startScreen_tweetFrom',
        'tweetTime': 'startScreen_tweetTime',
        'mobilegridcell_20': 'startScreen_mobilegridcell_20',
        'tweetText': 'startScreen_tweetText'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    OAuth2DS = new Appery.DataSource(TwitterRESTAuthService, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("startScreen");
        },
        'onSuccess': function(data) {
            try {
                SearchDS.execute({})
            } catch (ex) {
                console.log(ex.name + '  ' + ex.message);
                hideSpinner();
            };
        },
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['access_token'],
            'ID': '___js___',
            'ATTR': 'setToken',
            'TRANSFORMATION': function(value, element) {
                TwitSearchGlobal.bearerToken = value;
            }
        }],
        'requestMapping': [{
            'PATH': ['Authorization'],
            'TYPE': 'STRING',
            'HEADER': true,
            'TRANSFORMATION': function(value) {
                var parameter = TwitSearchGlobal.encodeBase64(TwitterSearchSettings['consumerKey'] + ":" + TwitterSearchSettings['consumerKeySecret']);
                return "Basic " + parameter;
            }
        }, {
            'PATH': ['grant_type'],
            'TYPE': 'STRING',
            'ATTR': 'client_credentials'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'https://api.twitter.com/oauth2/token'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1394812909741'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2787614'
        }]
    });

    datasources.push(OAuth2DS);

    SearchDS = new Appery.DataSource(TwitterSearch_SearchService, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("startScreen");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['statuses'],
            'ID': 'outputGrid',
            'SET': [{
                'PATH': ['user', 'name'],
                'ID': 'tweetFrom',
                'ATTR': '@'
            }, {
                'PATH': ['user', 'profile_image_url'],
                'ID': 'tweetPicture',
                'ATTR': 'src'
            }, {
                'PATH': ['created_at'],
                'ID': 'tweetTime',
                'ATTR': '@'
            }, {
                'PATH': ['text'],
                'ID': 'tweetText',
                'ATTR': '@'
            }]
        }],
        'requestMapping': [{
            'PATH': ['Authorization'],
            'TYPE': 'STRING',
            'HEADER': true,
            'TRANSFORMATION': function(value) {
                return "Bearer " + TwitSearchGlobal.bearerToken;
            }
        }, {
            'PATH': ['q'],
            'TYPE': 'STRING',
            'ID': 'searchInput',
            'ATTR': 'value'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'https://api.twitter.com/1.1/search/tweets.json'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1394812909744'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2788590'
        }]
    });

    datasources.push(SearchDS);

    /*
     * Events and handlers
     */

    // Before Show
    startScreen_beforeshow = function() {
        Appery.CurrentScreen = "startScreen";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_3671_onLoad = startScreen_onLoad = function() {
        screen_3671_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        startScreen_deviceEvents();
        startScreen_windowEvents();
        screen_3671_elementsEvents();
    }

    // screen window events
    screen_3671_windowEvents = startScreen_windowEvents = function() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    startScreen_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_3671_elementsExtraJS = startScreen_elementsExtraJS = function() {
        // screen (startScreen) extra code

    }

    // screen elements handler
    screen_3671_elementsEvents = startScreen_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#startScreen_mobilecontainer1 [name="searchButton"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    TwitSearchGlobal.beforeSearchTwit();

                }
            },
        });

    }

    $("#startScreen").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }

}

$("#startScreen").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    startScreen_js();
});